### ISSUE TITLE
Need to install dev rules after every startup

### ISSUE THREAD

**Issue by tothbar** [dagargo/overwitch#69] opened 2024-11-04 12:00 UTC
Hi, I'm using raspberry pi5 with a fresh install of rasbian arm64. For some reason I need to install the dev rules after every time I reboot the system. Do u know any solutions for this?

**Comment by szszoke** [comment] 2024-11-05 06:20
Can you post the output of the install script and can you check that the installed files are still there after reboot?

**Comment by tothbar** [comment] 2024-11-05 09:34
`make[1]: Entering directory '/home/tothbar/overwitch/udev'
make[1]: Nothing to be done for 'install-exec-am'.
 /usr/bin/mkdir -p '/lib/udev/hwdb.d'
 /usr/bin/install -c -m 644 20-usb-elektron.hwdb '/lib/udev/hwdb.d'
 /usr/bin/mkdir -p '/lib/udev/rules.d'
 /usr/bin/install -c -m 644 20-usb-elektron.rules '/lib/udev/rules.d'
make  install-data-hook
make[2]: Entering directory '/home/tothbar/overwitch/udev'
make[2]: Leaving directory '/home/tothbar/overwitch/udev'
make[1]: Leaving directory '/home/tothbar/overwitch/udev'`

after it I can see the the 20-usb-elektron-rules file, and also after reboot. 
Then I found out that the problem is that the Digitakt was plugged in before I booted the raspberry pi. If I replugged it in, it worked flawlessly, otherwise this is the error message I got:

'$ overwitch-cli -d Digitakt
ERROR:engine.c:750:ow_engine_init_from_bus_address: Error while opening device: LIBUSB_ERROR_ACCESS
ERROR:jclient.c:302:jclient_init: Overwitch error: can't find a matching device
'

so I guess I found the problem, sorry for taking your time. But if there would be a way to make the system recognize the device if it's plugged in before it started, that would make things even more stable.

thanks, Barnabás

**Comment by dagargo** [comment] 2024-11-05 10:27
That's a known problem with devices in Overbridge mode. At least, it happens to me every time I reboot my computer.

As you've said replugging the USB cable solves it. Changing the USB mode in the devices works too.

**Comment by tothbar** [comment] 2024-11-05 10:35
Thanks for your help guys!

**Comment by szszoke** [comment] 2024-11-05 10:42
I wonder if it would be enough to reset the USB ports.

Can you try to follow the answer from the post below and report back if it solved the issue?

https://unix.stackexchange.com/questions/234581/disconnect-and-reconnect-usb-port-via-cli#243457

**Comment by dagargo** [comment] 2024-11-05 17:59
I'll try to take a look at this because resetting the device manually is annoying.

**Comment by tothbar** [comment] 2024-11-05 18:43
okey, then I won't try now

**Comment by dagargo** [comment] 2024-11-06 23:17
I've noticed that the issue is that the udev rules are not applied at boot. At least not correctly.

The error `LIBUSB_ERROR_ACCESS` means [access denied (insufficient permissions)](https://libusb.sourceforge.io/api-1.0/group__libusb__misc.html#gab2323aa0f04bc22038e7e1740b2f29ef). 

```
$ overwitch-cli
ERROR:engine.c:757:ow_engine_init_from_bus_address: Error while opening device: LIBUSB_ERROR_ACCESS
ERROR:jclient.c:302:jclient_init: Overwitch error: can't find a matching device
```

Changing the permission manually fixes it. Digitakt is device `006` attached to bus `003`.

```
$ ls -la /dev/bus/usb/003/007
crw-rw-r-- 1 root root 189, 262 nov  6 23:28 /dev/bus/usb/003/007

$ sudo chmod 666 /dev/bus/usb/003/006
```

So the issue is outside the Overwitch code. But it might be on the udev rules definition though.

@tothbar, could you confirm that this solves your issue? At least we'll know where to look next.

**Comment by dagargo** [comment] 2024-11-08 16:17
Running `sudo udevadm trigger` forces the execution of the rules and fixes the issue.

Further research seems to indicate that the prefix `20` is to low to be applied correctly at boot and changing it to `91` as suggested [here](https://bbs.archlinux.org/viewtopic.php?id=196131) seems to have fixed it.

`fix-apply-udev-rules-at-boot` branch contains the fix.

@tothbar, take a look at the branch and once you confirm it works it will be merged into master. BTW, don't forget to run `make uninstall` from the `udev` directory before pulling the changes so that no old rules are installed.

**Comment by szszoke** [comment] 2024-11-10 14:52
`make uninstall` doesn't actually seem to remove anything on my system.

**Comment by dagargo** [comment] 2024-11-10 20:56
Thanks for reporting this, @szszoke.

Running `make uninstall` is fixed in `master` and `gtk3-overbridge-cc-midi` and deletes the rules as expected.

Also, branch `fix-apply-udev-rules-at-boot` incorporates the uninstaling code too.

Same situation as before. Don't forget to run `make uninstall` from the udev directory before pulling the changes of the `fix-apply-udev-rules-at-boot`. And once it's tested I'll merge it into master.

**Comment by szszoke** [comment] 2024-11-10 21:32
`make uninstall` in `master` and `fix-apply-udev-rules-at-boot` works now. I am rebooting now and report back if there are any permission issues.

**Comment by szszoke** [comment] 2024-11-10 21:35
I could not see permission issues after rebooting just my computer but not my DT2. Overwitch just worked.

**Comment by tothbar** [comment] 2024-11-15 22:12
got back to the project now.  Thanks guys for the fix, it works perfectly.

**Comment by tothbar** [comment] 2024-11-15 22:47
i made a script now, to lunch overwitch when usb is connected

`#!/bin/bash
sleep 1
sudo -u tothbar /usr/local/bin/overwitch-cli -d Digitone -v >> /var/log/usb-log.txt 2>&1

 
echo "Digitone-overwitch started" >> /var/log/usb-log.txt

`

created it with `sudo nano /usr/local/bin/run_overwitch_dt.sh
`
also run `sudo chmod +x /usr/local/bin/run_overwitch_dt.sh`

and made the udev rule with 
`sudo nano /etc/udev/rules.d/run_overwitch_dt.rules`

contains:
`ACTION=="add", SUBSYSTEM=="usb", ATTR{idVendor}=="1935", ATTR{idProduct}=="0b36", RUN+="/usr/local/bin/run_overwitch_dt.sh"
`

works perfeclty, its so much more convenient now!

**Comment by dagargo** [comment] 2024-11-16 09:08
That is really cool.

Would you like to add this to the `README.md`? I can do it myself too If you're OK with it.

Perhaps we could create a subsection at the end of the Installation section.

https://github.com/dagargo/overwitch?tab=readme-ov-file#installation

**Comment by tothbar** [comment] 2024-11-16 11:38
Ill! newer did something like this:)

**Comment by dagargo** [comment] 2024-11-23 07:25
Inspired by the @tothbar idea, I've just added an option to run `overwitch-cli` as a service. It uses USB hotplug to be notified when an Elektron device is plugged in.

```
$ overwitch-cli -s -vv
DEBUG:engine.c:1225:ow_hotplug_loop: Registering USB hotplug callback...
[...]
DEBUG:engine.c:1183:ow_hotplug_callback: USB hotplug: device arrived
DEBUG:main-cli.c:242:hotplug_callback: Starting new jclient for bus 003 and address 009...
DEBUG:main-cli.c:280:hotplug_callback: Pooled jclient 0 available...
[...]
```

This way, having a `systemd` unit works and there is no need for service restarts when plugging in devices.

```
/etc/systemd/user$ cat overwitch.service 
[Unit]
Description=Overwitch service

[Service]
GuessMainPID=true
ExecStart=overwitch-cli -b 8 -s
Restart=on-failure
```

Obviously, when running the service there is no need for the GUI whatsoever.

**Comment by dagargo** [comment] 2024-11-26 20:19
@tothbar, I've just added the documentation to the `README.md` in d68de3ba819b7285eb748cf8a10fe47452511f3d.

Take a look and, if you want to add something, create a new issue or a PR.

**Closed by dagargo** 2024-11-26 20:19 UTC

**Comment by tothbar** [comment] 2024-11-30 17:53
awesome! thanks
