### ISSUE TITLE
overwitch engine crashes when digitakt is connected via usb hub

### ISSUE THREAD

**Issue by dimashenme** [dagargo/overwitch#73] opened 2024-11-19 16:32 UTC
The problem occurs typically 3 to 9 minutes after the start of overwitch. The interface displays "error" in the "status" column and I need to press the refresh button to restart the overwitch engine. The following errors are printed to stderr:

> ERROR:engine.c:322:cb_xfr_audio_in: o2h: Error on USB audio transfer (0 B): LIBUSB_TRANSFER_ERROR
> ERROR:engine.c:349:cb_xfr_audio_out: h2o: Error on USB audio transfer (0 B): LIBUSB_TRANSFER_ERROR
> ERROR:engine.c:376:prepare_cycle_out_audio: h2o: Error when submitting USB audio out transfer: No such device (it may have been disconnected)

right after the crash dmesg says the following:

> [712742.014879] usb 1-2.2: USB disconnect, device number 14
> [712742.201516] usb 1-2.2: new high-speed USB device number 15 using xhci_hcd
> [712742.292368] usb 1-2.2: New USB device found, idVendor=1935, idProduct=0b2c, bcdDevice= 0.01
> [712742.292373] usb 1-2.2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
> [712742.292375] usb 1-2.2: Product: Elektron Digitakt
> [712742.292377] usb 1-2.2: Manufacturer: Elektron Music Machines
> [712742.292378] usb 1-2.2: SerialNumber: 000000000001
 

Digitakt is connected to the computer via TP-Link UH700 usb hub, the problem persists even if digitakt is the only device connected to the hub. The problem persists no matter what USB port the hub is connected to. I do not have other overbridge 2 devices to check whether the problem is digitakt-specific. The computer runs Ubuntu 20.04 and the os is not configured to suspend or go to power saving mode automatically.

**Comment by dagargo** [comment] 2024-11-26 20:38
Little can be done by Overwitch if the device is unplugged.

However, 872fb3f54f6f1767643c142648e4798756ea47ac adds USB hotplugging, which will reconnect to the device automatically.

@dimashenme, could you try this to see if it actually fixes your issue?

**Comment by dagargo** [comment] 2024-12-13 21:36
I'm closing this as the issue seemed to be caused by a disconnection.

As `overwitch-service` now includes hotplugging, this should not be an issue anymore. See the documentation for more about the service and how to install and run it under systemd.

Feel free to reopen if the issue persists and the device does not reconnect automatically.

**Closed by dagargo** 2024-12-13 21:36 UTC
